# Generated by Django 2.2.11 on 2021-05-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0234_auto_20210511_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='assigned_to_mbbs_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assigned_to_mbbs_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
